# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f259850275b5d03d8be98f9aa0afdc95a89593cd2a6957b20ea4c0368b83c1ea4b714d6c383146342c3d08b9de1378830255d36da509ed43c9ec5cc960f356

test:
  secret_key_base: 2e2d47f360e41112665c7af37bb94679b015720ce54eb9f819366a249c99ff1435df19e03fe2b39295412123a4d28357687847a60730cd1b4b97c307c9323ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
